
favicon: /img/pixiv1.jpg

avatar:
  img: /img/shiyijuxiawula.jpg
  effect: true         

index_img: /img/pixiv2.jpg
default_top_img: /img/pixiv2.jpg

background: /img/pixiv3.jpg

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:
    - /img/pixiv2.jpg

error_img:
  flink: /img/pixiv3.jpg
  post_page: /img/pixiv2.jpg